# Generated by Django 4.1.7 on 2024-02-01 11:05

import account.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=24, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=24, verbose_name='Имя')),
                ('patronimic', models.CharField(blank=True, max_length=24, verbose_name='Отчество')),
                ('ITN', models.PositiveBigIntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(999999999999)], verbose_name='ИНН')),
                ('post', models.CharField(max_length=24, verbose_name='Должность')),
                ('dependents', models.IntegerField(default=0, verbose_name='Иждивенцы')),
                ('employment_date', models.DateField(null=True, verbose_name='Дата приёма')),
                ('description', models.TextField(blank=True, max_length=150, verbose_name='Описание')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Сотрудники',
                'verbose_name_plural': 'Персонал',
                'ordering': ['surname'],
            },
        ),
        migrations.CreateModel(
            name='Accruals_and_taxes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(verbose_name='Дата выплаты')),
                ('reporting_date', models.DateField(blank=True, default=account.models.default_datetime, null=True, verbose_name='Дата начисления')),
                ('accrued', models.FloatField(verbose_name='Начислено')),
                ('alimony', models.FloatField(default=0, verbose_name='Алименты в %')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.staff', verbose_name='Работник')),
            ],
            options={
                'verbose_name': 'Выплата',
                'verbose_name_plural': 'Выплаты',
            },
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['surname'], name='account_sta_surname_a730b0_idx'),
        ),
    ]
