# Generated by Django 4.1.7 on 2024-03-02 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accruals_and_taxes',
            name='social_ded',
            field=models.FloatField(default=0, verbose_name='Соц.вычет уч.'),
        ),
    ]
